# Generated by Django 5.0.6 on 2024-12-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='order',
            field=models.ImageField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
