# Generated by Django 5.0.6 on 2024-12-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_employees_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='order',
            field=models.IntegerField(),
        ),
    ]
