# Generated by Django 5.0.6 on 2024-12-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_searchhistory_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='missing_word',
            field=models.CharField(default=2, max_length=250),
            preserve_default=False,
        ),
    ]
