# Generated by Django 5.0.6 on 2024-12-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_searchhistory_missing_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='source',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
