# Generated by Django 5.0.6 on 2024-12-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_contact_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='publications/')),
                ('file', models.FileField(upload_to='publications/pdf/')),
                ('text', models.TextField(max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
