# Generated by Django 5.1.4 on 2024-12-27 12:27

import django.db.models.deletion
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_words_comment_words_grammatical_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('location_name', models.CharField(max_length=255)),
                ('location_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='CategoryProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kategoriyaning nomi')),
            ],
            options={
                'verbose_name': 'Category Project',
                'verbose_name_plural': 'Category Projects',
            },
        ),
        migrations.CreateModel(
            name='AboutProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasnif', ckeditor.fields.RichTextField(blank=True, help_text="Loyha haqida to'liq qollanma yozing", verbose_name='Loyha tasnifi (Qollanma)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyhalar', to='data.categoryproject', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'About Project',
                'verbose_name_plural': 'About Projects',
            },
        ),
    ]
