name: Deploy Dictionary with Docker and SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Kodni yuklab olish
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Docker Hub'ga login qilish
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # 3. Docker image yaratish va push qilish
    - name: Build and push Docker image
      run: |
        docker build -t dictionary:${{ github.sha }} .
        docker tag dictionary:${{ github.sha }} asadbek2/dictionary:latest
        docker push asadbek2/dictionary:latest

    # 4. Serverga ulanish va Docker containerni ishga tushirish
    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.11
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          # Docker Compose'ni yangilash (docker-compose.yml faylini serverga yuborish)
          echo "Yuborish docker-compose.yml faylini"
          scp -i ${{ secrets.SERVER_SSH_KEY }} docker-compose.yml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/${{ secrets.SERVER_USER }}/

          # Docker konteynerlarini ishga tushirish
          cd /home/${{ secrets.SERVER_USER }}
          docker-compose down
          docker-compose up -d
